services:
  producer:
    image: openjdk:21-slim-buster
    working_dir: /home/app/spring
    entrypoint: "bash -c \"./mvnw clean package && java -jar target/producer-1.0.0.jar\""
    environment:
      JAVA_TOOL_OPTIONS: "-XX:UseSVE=0"
      API_PORT: 8081
      API_LOGGING_LEVEL: info
      KAFKA_HOST: kafka
      KAFKA_PORT: 9092
    ports:
      - 8081:8081
    volumes:
      - ${PWD}/producer:/home/app/spring
    networks:
      - ed_demo
    profiles:
      - pre

  kafka:
    image: apache/kafka-native:latest
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_LISTENERS: PLAINTEXT://:9092,CONTROLLER://:9093
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka:9093
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_NUM_PARTITIONS: 3
    networks:
      - ed_demo
    profiles:
      - dev
      - pre
  
  kafdrop:
    image: obsidiandynamics/kafdrop:4.1.0
    depends_on:
      - kafka
    ports:
      - 9000:9000
    environment:
      KAFKA_BROKERCONNECT: kafka:9092
      JVM_OPTS: "-Xms32M -Xmx64M"
    networks:
      - ed_demo
    profiles:
      - dev
      - pre

networks:
  ed_demo: