server:
  port: ${API_PORT:8081}

logging:
  level:
    '[org.springframework.web]': ${API_LOGGING_LEVEL:info}

springdoc:
    swagger-ui:
        path: /swagger-ui.html

spring:
    application:
        name: producer
    kafka:
      producer:
        bootstrap-servers: ${KAFKA_HOST:localhost}:${KAFKA_PORT:9092}
        key-serializer: org.apache.kafka.common.serialization.StringSerializer
        value-serializer: org.apache.kafka.common.serialization.StringSerializer
