name: CI Pipeline

on:
  push:
    branches: [ "develop", master ]
  pull_request:
    branches: [ "develop" ]
  workflow_dispatch:

permissions:
  pull-requests: read

jobs:
  Sonar-Cloud:
    runs-on: ubuntu-latest

    steps:
      - name: Analyze with SonarCloud
        uses: SonarSource/sonarqube-scan-action@v4
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          args:
            -Dsonar.projectKey=Armando-Torres_event-driven
            -Dsonar.organization=armando-torres